### ISSUE TITLE
Operations throwing ArgumentError in v2.0.0

### ISSUE THREAD

**Issue by clarkedb** [rudderlabs/rudder-sdk-ruby-sync#9]
## Overview

Operations like `track` are broken in v2.0.0 of the `rudder_analytics_sync` gem. Calling them results in an unhandled exception:

```text
ArgumentError: wrong number of arguments (given 1, expected 2)
```

## Steps to Reproduce

1. Install the gem `rudder_analytics_sync` at v2.0.0
2. Run the code below in `irb` or in a ruby script.
```ruby
client = RudderAnalyticsSync::Client.new(
  stub: false,
  write_key: 'my_key_here',
  data_plane_url: 'https://my-dataplane.rudderstack.com',
  on_error: proc { |error_code, error_body, exception, response|
    puts(error_code, error_code, error_body, exception, response)
  },
)

client.track(
  user_id: 'user_id_1',
  event: 'my event',
  properties: { my_prop: 'value' },
)
```

### Expected Result:

Successful network request.

### Actual Result:

```text
RUBY_PATH/gems/rudder_analytics_sync-2.0.0/lib/rudder_analytics_sync/request.rb:24:in `post': wrong number of arguments (given 1, expected 2) (ArgumentError)
	from RUBY_PATH/gems/rudder_analytics_sync-2.0.0/lib/rudder_analytics_sync/operations/track.rb:14:in `call'
	from RUBY_PATH/gems/rudder_analytics_sync-2.0.0/lib/rudder_analytics_sync/client.rb:40:in `track'
	from (irb):38:in `<main>'
	from RUBY_PATH/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
	from RUBY_PATH/bin/irb:25:in `load'
	from RUBY_PATH/bin/irb:25:in `<main>'
	from RUBY_PATH/bin/ruby_executable_hooks:22:in `eval'
	from RUBY_PATH/bin/ruby_executable_hooks:22:in `<main>'
```

## Likely Cause

The operations used to have `call` methods like the `Operations::Track#call` method below:

```ruby
def call
  request.post('/v1/track', build_payload)
end
```

They were updated in #6 to

```ruby
def call
  batch = build_payload.merge(
    type: 'track'
  )
  if batch.inspect.length > MAX_MESSAGE_SIZE
    raise ArgumentError, 'Max message size is 32 KB'
  end

  request.post('/v1/batch', batch: [batch])
end
```

It's the last line `request.post('/v1/batch', batch: [batch])` that is failing. The call signature of the method `Request#post` did not change. It expects a url and a payload and supports a keyword argument `:headers`. The new code calls `post` with only the url (no payload argument) and an unrecognized keyword argument `:batch`.

This error is present in all of the `Operation` classes.

**Comment by pallabmaiti** [comment]
Which Ruby version you are using?

**Comment by clarkedb** [comment]
> Which Ruby version you are using?

I tested on Ruby 3.0, 3.1, 3.2 and had the same error. I did not try 2.7.
